# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, verbose_name='関数名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, default=0, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, verbose_name='タグ名'),
        ),
    ]
