# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160513_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.CharField(blank=True, max_length=255, verbose_name='作成者'),
        ),
    ]
