# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20160513_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='func_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='book',
            name='page',
        ),
        migrations.AddField(
            model_name='book',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='プログラム名'),
        ),
    ]
