# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20160513_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='program_name',
            field=models.CharField(max_length=255, verbose_name='プログラム名'),
        ),
    ]
