# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.Book', verbose_name='関数名'),
        ),
    ]
