# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.CharField(blank=True, max_length=255, verbose_name='test'),
        ),
    ]
