# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\x1b$B=q@RL>\x1b(B')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='\x1b$B=PHG<R\x1b(B')),
                ('page', models.IntegerField(blank=True, default=0, verbose_name='\x1b$B%Z!<%8?t\x1b(B')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='\x1b$B%3%a%s%H\x1b(B')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.Book', verbose_name='\x1b$B=q@R\x1b(B')),
            ],
        ),
    ]
