# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160518_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, default=0, verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, verbose_name='publisher'),
        ),
    ]
